name: url parse

on: push

jobs:
  job1:
    name: first step
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          echo 'start get urls'
          find . -name "*.gif" > urls.txt
      - name: download txt file
        uses: actions/upload-artifact@v1
        with:
          name: homework
          path: urls.txt
