name: url parse

on: push

jobs:
  job1:
    name: first step
    runs-on: ubuntu-latest
    steps:
      - name: start parsing...
        shell: bash
        run: |
          echo 'start get urls'
          find . -name "*.gif"
